version: "3.1"

services:

  mongo:
    image: mongo
    container_name: mongo
    restart: always
  
  backend:
    depends_on:
      - mongo
    build: .
    restart: always
    ports:
      - 8080:8080